### ISSUE TITLE
Unable to parse metric

### ISSUE THREAD

**Issue by diptanu** [sethfitz/metricsd#17]
MetricsD is unable to parse the following metric
Foo.Web.ServiceHost.QueueWorker.ExternalAnalyticsEventMessage.PendingMessages:3.000000000000000|g

ERROR [2013-11-21 00:36:08,585] net.mojodna.metricsd.server.MetricsServiceHandler: Exception in MetricsServiceHandler
! scala.MatchError: Foo.Web.ServiceHost.QueueWorker.ExternalAnalyticsEventMessage.PendingMessages:3.000000000000000|g (of class java.lang.String)
!   at net.mojodna.metricsd.server.MetricsServiceHandler$$anonfun$messageReceived$1.apply(MetricsServiceHandler.scala:34)
!   at net.mojodna.metricsd.server.MetricsServiceHandler$$anonfun$messageReceived$1.apply(MetricsServiceHandler.scala:32)
!   at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
!   at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
!   at net.mojodna.metricsd.server.MetricsServiceHandler.messageReceived(MetricsServiceHandler.scala:31)
!   at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
!   at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70)
!   at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
!   at org.jboss.netty.channel.socket.nio.NioDatagramWorker.read(NioDatagramWorker.java:98)
!   at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)

**Comment by sethfitz** [comment]
Values need to be integers at the moment (meaning that decimal values need to be scaled before sent to metricsd).  `3.000000000000000|g` should be `3|g`.

I think I originally limited it to ints because Graphite needs to see ints, but aggregations shouldn't care...
